name: DNSTwist Domain Monitor

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  scan-domains:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dnstwist requests dnspython
          
      - name: Run DNSTwist scan and compare
        run: python .github/scripts/dnstwist_monitor.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Pull Request if changes detected
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update domain monitoring results
          title: 'feat: Update domain monitoring results'
          body: |
            New potentially malicious domains detected.
            This PR was automatically created by the DNSTwist monitoring workflow.
          branch: update-domain-monitoring
          delete-branch: true